image: gitpod/workspace-full:latest

tasks:
    - init: ./init.sh
      command: |
        echo "$(date) a command was here"
        echo "$(date) $(cat /workspace/.gitpod/ready)"
        echo "$(date) $(cat /workspace/init-test)"
