image: gitpod/workspace-full:latest

tasks:
    - init: ${GITPOD_REPO_ROOT}/init.sh
      command: echo 'some task'
    - name: headless-test
      init: |
        if [[ -n "$GITPOD_HEADLESS:-" ]]; then
          echo "is-headless $(date) >> /workspace/at-init
        fi
        sleep 10
        echo "done $(date) >> /workspace/headless-test
